In [1]:
import sys

!conda install --yes --prefix {sys.prefix} pandas
!{sys.executable} -m pip install nba_api

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Requirement already satisfied: nba_api in /home/caspera/.conda/envs/lab/lib/python3.9/site-packages (1.1.10)
Requirement already satisfied: requests in /home/caspera/.conda/envs/lab/lib/python3.9/site-packages (from nba_api) (2.26.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/caspera/.conda/envs/lab/lib/python3.9/site-packages (from requests->nba_api) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in /home/caspera/.conda/envs/lab/lib/python3.9/site-packages (from requests->nba_api) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /home/caspera/.conda/envs/lab/lib/python3.9/site-packages (from requests->nba_api) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/caspera/.conda/envs/lab/lib/python3.9/site-packages (from requests->nba_api) (2.0.4)

In [45]:
from nba_api.stats.static import players as nba_players

def get_selected_player_names():
    return [line.rstrip("\n") for line in open("./data/players.txt").readlines()]

def get_player(full_name):
    for player in nba_players.get_players():
        if player["full_name"] == full_name:
            return player

def get_selected_players():
    selected_players = []
    for player_name in get_selected_player_names():
        selected_players.append(get_player(player_name))
    
    return selected_players

player = get_player("Wilt Chamberlain")
player

{'id': 76375,
 'full_name': 'Wilt Chamberlain',
 'first_name': 'Wilt',
 'last_name': 'Chamberlain',
 'is_active': False}

In [46]:
from nba_api.stats.endpoints import playercareerstats

stats = ["MIN", "FGM", "REB", "AST", "STL", "BLK", "TOV", "PF", "PTS"]

def add_per_game_stats(df):
    for stat in stats:
        df[stat + "_PG"] = df[stat] / df["GP"]

def add_per_minute_stats(df):
    for stat in stats:
        df[stat + "_PM"] = df[stat + "_PG"] / df["MIN_PG"]

career = playercareerstats.PlayerCareerStats(player_id=player["id"])
df = career.get_data_frames()[0]
add_per_game_stats(df)
add_per_minute_stats(df)
df

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,PTS_PG,MIN_PM,FGM_PM,REB_PM,AST_PM,STL_PM,BLK_PM,TOV_PM,PF_PM,PTS_PM
0,76375,1959-60,00,1610612744,PHW,23.0,72,None,3338.0,1065,...,37.597222,1.0,0.319053,0.581486,0.050330,NaN,NaN,NaN,0.044937,0.810965
1,76375,1960-61,00,1610612744,PHW,24.0,79,None,3773.0,1251,...,38.392405,1.0,0.331566,0.569573,0.039226,NaN,NaN,NaN,0.034455,0.803870
2,76375,1961-62,00,1610612744,PHW,25.0,80,None,3882.0,1597,...,50.362500,1.0,0.411386,0.528594,0.049459,NaN,NaN,NaN,0.031685,1.037867
3,76375,1962-63,00,1610612744,SFW,26.0,80,None,3806.0,1463,...,44.825000,1.0,0.384393,0.511298,0.072254,NaN,NaN,NaN,0.035733,0.942197
4,76375,1963-64,00,1610612744,SFW,27.0,80,None,3689.0,1204,...,36.850000,1.0,0.326376,0.484413,0.109244,NaN,NaN,NaN,0.049336,0.799133
5,76375,1964-65,00,1610612755,PHL,28.0,35,None,1558.0,427,...,30.114286,1.0,0.274069,0.500642,0.085366,NaN,NaN,NaN,0.044929,0.676508
6,76375,1964-65,00,1610612744,SFW,28.0,38,None,1743.0,636,...,38.947368,1.0,0.364888,0.512335,0.067126,NaN,NaN,NaN,0.043603,0.849111
7,76375,1964-65,00,0,TOT,28.0,73,None,3301.0,1063,...,34.712329,1.0,0.322024,0.506816,0.075735,NaN,NaN,NaN,0.044229,0.767646
8,76375,1965-66,00,1610612755,PHL,29.0,79,None,3737.0,1074,...,33.531646,1.0,0.287396,0.519936,0.110784,NaN,NaN,NaN,0.045759,0.708857
9,76375,1966-67,00,1610612755,PHL,30.0,81,None,3682.0,785,...,24.148148,1.0,0.213199,0.531505,0.171103,NaN,NaN,NaN,0.038838,0.531233
10,76375,1967-68,00,1610612755,PHL,31.0,82,None,3836.0,819,...,24.292683,1.0,0.213504,0.508863,0.183003,NaN,NaN,NaN,0.041710,0.519291
11,76375,1968-69,00,1610612747,LAL,32.0,81,None,3669.0,641,...,20.543210,1.0,0.174707,0.466612,0.099755,NaN,NaN,NaN,0.038703,0.453530
12,76375,1969-70,00,1610612747,LAL,33.0,12,None,505.0,129,...,27.333333,1.0,0.255446,0.437624,0.097030,NaN,NaN,NaN,0.061386,0.649505
13,76375,1970-71,00,1610612747,LAL,34.0,82,None,3630.0,668,...,20.682927,1.0,0.184022,0.411295,0.096970,NaN,NaN,NaN,0.047934,0.467218
14,76375,1971-72,00,1610612747,LAL,35.0,82,None,3469.0,496,...,14.792683,1.0,0.142981,0.453157,0.094840,NaN,NaN,NaN,0.056500,0.349668
15,76375,1972-73,00,1610612747,LAL,36.0,82,None,3542.0,426,...,13.219512,1.0,0.120271,0.430830,0.103049,NaN,NaN,NaN,0.053924,0.306042